title: "Paul Martinez"
description: "Portfolio et blog de Paul Martinez"
url: "https://paulmrtnz.github.io"
baseurl: ""
lang: fr
timezone: Europe/Paris
author: Paul Martinez
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Paul Martinez
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

permalink: /blog/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - qrcodemaker.py
  - README.md
  - vendor/
  - .bundle/
  - _site/
